import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.scss'
import React, { useState } from 'react'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import Button from '@components/Button/Button'
import {
  decrement,
  increment,
  incrementByAmount,
  countSelector,
  getKanyeQuote,
  kanyeQuoteSelector
} from '@store/index'

const Home: NextPage = () => {
  const dispatch = useAppDispatch()
  const count = useAppSelector(countSelector)
  const [incrementAmount, setIncrementAmount] = useState<number>(0)
  const { data, pending, error } = useAppSelector(kanyeQuoteSelector)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Counter Redux &rarr;</h2>
            <p>Value: {count}</p>
            <input
              value={incrementAmount}
              onChange={e => setIncrementAmount(Number(e.target.value))}
              type="number"
            />
            <Button onClick={() => dispatch(decrement())}>Decrement</Button>
            <Button onClick={() => dispatch(increment())}>Increment</Button>
            <Button
              onClick={() =>
                dispatch(incrementByAmount(Number(incrementAmount)))
              }
            >
              Increment by amount
            </Button>
            <Button
              onClick={() => dispatch(incrementByAmount(Number(count * -1)))}
              disabled={pending}
            >
              Reset
            </Button>
          </div>
          <div className={styles.card}>
            <h2>Fetch Redux &rarr;</h2>
            <div>
              <p>Generate random Kanye West quote</p>
              {pending && <span>Loading...</span>}
              {data && <span>{data.quote}</span>}
              {error && <span>Oops, something went wrong</span>}
              <br />
              <Button
                onClick={() => dispatch(getKanyeQuote())}
                disabled={pending}
              >
                Generate Kanye Quote
              </Button>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
